---
- hosts: masters
  remote_user: centos
  become: yes
  become_method: sudo
  become_user: root

  gather_facts: no
  vars:
    token_path: /etc/kubernetes/join_token

  tasks:
    - name: Token publish
      shell:  kubeadm token create --print-join-command
      register: token
    
    - debug: msg="{{token.stdout}}"  
    - name: Register dummy host with variable
      add_host:
       name: "DUMMY_HOST"
       TOKEN_NEW: "{{token.stdout}}"

- hosts: workers
  remote_user: centos
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Join worker cluster
      shell: "{{hostvars['DUMMY_HOST']['TOKEN_NEW']}}"
      register: TOKEN2_RESULTS
      ignore_errors: yes
    - debug: msg="{{TOKEN2_RESULTS.stdout}}"
